### ISSUE TITLE
I have one different Markbot request, could you please double check when you have a min :)

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/pretty-products#1]
@hellachella
@carolsinc

**Comment by carolsinc** [comment]
line 46 of css, border radius should be on its own line

**Comment by carolsinc** [comment]
In the html the main should start directly below the body

**Comment by carolsinc** [comment]
I think you may have just copy and pasted multiple times, everything between the opening of your body and the opening of your main can just be deleted
